mmorpg/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newsboard/', include('newsboard.urls')),
    path('auth/', include('authentication.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg/newsboard/urls.py
from django.urls import path

from .views import *

app_name = 'newsboard'
urlpatterns = [

    # -----------------posts---------------------
    path('', PostList.as_view(), name='home'),
    path('<int:pk>', PostDetail.as_view(), name='detail'),
    path('create/', PostCreate.as_view(), name='create'),
    path('update/<int:post_pk>', PostUpdate.as_view(), name='update'),
    # -----------------endposts---------------------

    # -----------------comments---------------------
    path('<int:post_pk>/comments', CommentsList.as_view(), name='post_comments'),
    path('<int:post_pk>/create_comment', CommentCreate.as_view(), name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/confirm', CommentConfirm.as_view(), name='comment_confirm'),
    path('<int:post_pk>/comments/<int:comment_pk>/reject', CommentReject.as_view(), name='comment_reject'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete', CommentDelete.as_view(), name='comment_delete'),
    path('my_comments/', MyComments.as_view(), name='my_comments'),
    # -----------------endcomments---------------------
]

mmorpg/newsboard/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=256)
    text = RichTextUploadingField('Текст')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')

    date_of_creation = models.DateField(auto_now_add=True)
    time_of_creation = models.TimeField(auto_now_add=True)
    datetime_of_creation = models.DateTimeField(auto_now_add=True)

    date_of_last_update = models.DateField(auto_now=True)
    time_of_last_update = models.TimeField(auto_now=True)
    datetime_of_last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.category} {self.title}'


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=1500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    confirmed = models.BooleanField('Подтвержден', null=True, blank=True)

    date_of_creation = models.DateField(auto_now_add=True)
    time_of_creation = models.TimeField(auto_now_add=True)
    datetime_of_creation = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author} {self.date_of_creation} {self.time_of_creation.__format__("%H:%M:%S")}'

mmorpg/newsboard/forms.py
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms

from .models import *


class PostCreateForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        label='Категория',
        widget=forms.Select(attrs={'class': 'form-select'}),
        queryset=Category.objects.all()
    )
    title = forms.CharField(label='Заголовок', widget=forms.TextInput(attrs={'class': 'form-control'}))
    text = forms.CharField(label='Текст', widget=CKEditorUploadingWidget(attrs={'class': 'form-control'}))

    class Meta:
        model = Post
        exclude = ('author',)


class CommentCreateForm(forms.ModelForm):
    text = forms.CharField(label='Текст', widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('text',)

mmorpg/newsboard/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from .forms import PostCreateForm, CommentCreateForm
from .models import *
from .utils.permissions import IsAuthorMixin, NotIsAuthorMixin


class PostList(ListView):
    model = Post
    context_object_name = 'post_list'
    queryset = Post.objects.order_by('-datetime_of_last_update')


class PostDetail(DetailView):
    model = Post
    context_object_name = 'post'


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'newsboard/post_create.html'

    def get_success_url(self):
        return reverse('newsboard:home')

    def form_valid(self, form):
        post = form.save(commit=False)
        user = self.request.user
        post.author = user
        return super().form_valid(form)


class PostUpdate(IsAuthorMixin, UpdateView):
    model = Post
    pk_url_kwarg = 'post_pk'
    form_class = PostCreateForm
    template_name = 'newsboard/post_create.html'

    def get_success_url(self):
        return reverse('newsboard:home')

    def form_valid(self, form):
        messages.success(self.request, 'Запись успешно обновлена!')
        return super().form_valid(form)


class CommentsList(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        post_pk = kwargs['post_pk']
        post = Post.objects.get(pk=post_pk)
        qs = Comment.objects.order_by('datetime_of_creation').filter(post=post)

        context = {
            'comments': qs,
            'post': post
        }

        return render(request, 'newsboard/post_comments.html', context)


class CommentCreate(NotIsAuthorMixin, View):
    def get(self, request, **kwargs):
        form = CommentCreateForm(request.POST or None)
        post = Post.objects.get(pk=kwargs['post_pk'])

        context = {
             'form': form,
             'post': post
         }

        return render(request, 'newsboard/comment_create.html', context)

    def post(self, request, *args, **kwargs):
        form = CommentCreateForm(request.POST)
        user = request.user
        post_pk = kwargs['post_pk']

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = user
            comment.post = Post.objects.get(pk=post_pk)
            comment.save()

        return redirect('newsboard:home')


class CommentConfirm(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.confirmed = True
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentReject(IsAuthorMixin, View):
    def get(self, request, *args, **kwargs):
        comment_pk = kwargs['comment_pk']

        comment = Comment.objects.get(pk=comment_pk)
        comment.confirmed = False
        comment.save()

        return redirect(request.META['HTTP_REFERER'])


class CommentDelete(DeleteView):
    pass


class MyComments(View):
    def get(self, request, *args, **kwargs):
        context = {
            'posts': request.user.post_set.all(),
        }
        return render(request, 'newsboard/my_comments.html', context)

mmorpg/newsboard/templates/newsboard/base.html
{% load main_menu %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block titile %}{% endblock titile %}</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<body>
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
          {% get_items_for_main_menu request as get_items_for_main_menu %}
          {% for item in get_items_for_main_menu %}
                <li><a href="{% url item.url_name %}" class="nav-link px-2 link-secondary">{{ item.title }}</a></li>
          {% endfor %}
      </ul>

      <div class="col-md-3 text-end">
          {% if request.user.is_authenticated %}
              <button type="button" class="btn btn-outline-primary me-2 bg-light text-dark">{{ request.user }}</button>
              <a href="{% url 'account_logout' %}"><button type="button" class="btn btn-primary">Выйти</button></a>
          {% else %}
              <a href="{% url 'account_login' %}">
                  <button type="button" class="btn btn-outline-primary me-2">
                      Войти
                  </button>
              </a>
              <a href="{% url 'account_signup' %}">
                  <button type="button" class="btn btn-primary">
                      Регистрация
                  </button>
              </a>
          {% endif %}
      </div>
    </header>
  </div>

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}

{% block content %}
{% endblock content %}

  {% include 'template_particles/footer.html' %}
</body>
</html>

mmorpg/newsboard/templates/newsboard/comment_create.html
{% extends 'newsboard/base.html' %}

{% block titile %}Добавление отклика{% endblock titile %}

{% block content %}
<div class="container-fluid">
    <div class="card-body">
        <div class="p-3 mb-2 bg-danger text-dark">
            <h3><span class="badge bg-secondary float-end">{{ post.category }}</span></h3>
            <h5 class="card-title">{{ post.title }}</h5>
        </div>
</div>
    <div class="container">
        <h2 class="mb-4 mt-5">Добавить отклик:</h2>

        <form method="post" class="row g-3">
            {% csrf_token %}

            <div class="col-12">
                <p>{{ form.text.label_tag }}</p>
                {{ form.text }}
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary">Добавить</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

mmorpg/newsboard/templates/newsboard/my_comments.html
{% extends 'newsboard/base.html' %}

{% block content %}
<div class="row">
    {% for post in posts %}
        <div class="col-9">
            <div class="card-body">
                <a class="navbar-brand" href="{% url 'newsboard:post_comments' post.pk %}">
                    <div class="p-3 mb-2 bg-danger text-dark">
                        <h3><span class="badge bg-secondary float-end">{{ post.category }}</span></h3>
                        <h5 class="card-title">{{ post.title }}</h5>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-3">
            <a href="{% url 'newsboard:post_comments' post.pk %}">
                <button type="button" class="btn btn-lg btn-outline-primary position-relative me-sm-3 mb-sm-3 mt-3">
                    Отклики
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    {{ post.comment_set.all|length }}
                    </span>
                </button>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock content %}

mmorpg/newsboard/templates/newsboard/post_comments.html
{% extends 'newsboard/base.html' %}

{% block content %}

<div class="container">
    <div class="card-body">
        <div class="p-3 mb-2 bg-danger text-dark">
            <h3><span class="badge bg-secondary float-end">{{ post.category }}</span></h3>
            <h5 class="card-title">{{ post.title }}</h5>
        </div>
    </div>
    <div class="list-group mt-3 ms-3">
        {% for comment in comments %}
            <div class="shadow-sm p-3 mb-5 bg-body rounded">
                <div class="d-flex w-100 justify-content-between mt-1">
                    <h5 class="mb-1">{{ comment.author }}</h5>
                    <small class="text-muted">{{ comment.datetime_of_creation }}</small>
                </div>
                <div class="row">
                    <div class="col-9"><p class="mb-1 ms-3">{{ comment.text }}</p></div>
                    {% if post in user.post_set.all %}
                        {% if comment.confirmed %}
                            <div class="col-3">
                                <button class="btn btn-outline-success mt-2">
                                        Подтвержден
                                </button>
                                <a href="{% url 'newsboard:comment_reject' post.pk comment.pk %}">
                                    <button class="btn btn-danger mt-2">
                                        Отклонить
                                    </button>
                                </a>
                            </div>
                        {% elif comment.confirmed is None %}
                            <div class="col-3">
                                <a href="{% url 'newsboard:comment_confirm' post.pk comment.pk %}">
                                    <button class="btn btn-success mt-2">
                                        Принять
                                    </button>
                                </a>
                                <a href="{% url 'newsboard:comment_reject' post.pk comment.pk %}">
                                    <button class="btn btn-danger mt-2">
                                        Отклонить
                                    </button>
                                </a>
                            </div>
                        {% elif not comment.confirmed %}
                            <div class="col-3">
                                <button class="btn btn-outline-danger mt-2">
                                        Отклонен
                                </button>
                                <a href="{% url 'newsboard:comment_confirm' post.pk comment.pk %}">
                                    <button class="btn btn-success mt-2">
                                        Принять
                                    </button>
                                </a>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% empty %}
            <div class="px-4 py-5 my-5 text-center">
                <h1 class="display-5 fw-bold">Тут пусто!</h1>
                <div class="col-lg-6 mx-auto">
                    <p class="lead mb-4">У данного поста пока что нет ни одного отклика.</p>
                    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                        <a href="{% url 'newsboard:home' %}">
                            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">
                                К новостям
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

mmorpg/newsboard/templates/newsboard/post_create.html
{% extends 'newsboard/base.html' %}
{% load static %}

{% block titile %}Добавление новости{% endblock titile %}

{% block content %}

<div class="container">
    <h2 class="mb-5">Добавление записи:</h2>
    <form method="post" class="row g-3">
        {% csrf_token %}
        <div class="col-md-4">
          {{ form.category.label_tag }}
          {{ form.category }}
        </div>
        <div class="col-8">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>
            {{ form.text.label_tag }}
            {{ form.text }}
        <div class="col-12">
            {{ form.media }}
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
    </form>
</div>

{% endblock content %}

mmorpg/newsboard/templates/newsboard/post_detail.html
{% extends 'newsboard/base.html' %}

{% block titile %}{{ post }}{% endblock titile %}

{% block content %}
<div class="row mt-5">
    <div class="col-lg-12">
        <div class="shadow p-3 mb-3 bg-body rounded">
            <div class="card">
                <div class="card-body">
                    <div class="p-3 mb-2 bg-danger text-dark">
                        <h3><span class="badge bg-secondary float-end">{{ post.category }}</span></h3>
                        <h5 class="card-title">{{ post.title }}</h5>
                    </div>
                    <div class="col-lg-4 float-end">
                        {% if user.is_authenticated %}
                            <div class="container">
                                <div class="card-body">
                                    {% if post in user.post_set.all %}
                                        <a href="#">
                                        <button type="button" class="btn btn-lg btn-outline-primary position-relative me-sm-3 mb-sm-3 mt-3">
                                            Отклики
                                            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                            {{ post.comment_set.all|length }}
                                            </span>
                                        </button>
                                        </a>
                                        <a href="{% url 'newsboard:update' post.pk %}">
                                            <button class="btn btn-lg btn-outline-primary me-sm-3 mb-sm-3 mt-3">
                                                Редактировать
                                            </button>
                                        </a>
                                        <a href="#">
                                            <button class="btn btn-lg btn-outline-danger me-sm-3 mb-sm-3 mt-3">
                                                Удалить
                                            </button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <p class="card-text mt-5 mb-5 ms-4 me-4">{{  post.text|safe }}</p>

                    <p class="card-text">
                        <small class="text-muted ms-1">
                            Последнее обновление: {{ post.date_of_last_update }} {{ post.time_of_last_update }}
                        </small>
                        <span class=" ms-3 float-end">Автор: {{ post.author }}</span>
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

mmorpg/newsboard/templates/newsboard/post_list.html
{% extends 'newsboard/base.html' %}

{% block titile %}Новости{% endblock titile %}

{% block content %}

<div class="container-fluid ms-5">
    {% for post in post_list %}
        <div class="row mt-5">
            <div class="col-lg-8">
                <div class="shadow p-3 mb-3 bg-body rounded">
                    <div class="card">
                        <div class="card-body">
                            <a class="navbar-brand" href="{% url 'newsboard:detail' post.pk %}">
                                <div class="p-3 mb-2 bg-danger text-dark">
                                    <h3><span class="badge bg-secondary float-end">{{ post.category }}</span></h3>
                                    <h5 class="card-title">{{ post.title }}</h5>
                                </div>
                            </a>
                            <div class="container">
                                <p class="card-text mt-5 mb-5 ms-4 me-4">{{  post.text|safe|truncatewords:'100' }}</p>
                                <a class="btn btn-primary mb-5" href="{% url 'newsboard:detail' post.pk %}">
                                    Читать далее...
                                </a>
                            </div>

                            <p class="card-text">
                                <small class="text-muted ms-1">
                                    Последнее обновление: {{ post.date_of_last_update }} {{ post.time_of_last_update }}
                                </small>
                                <span class=" ms-3 float-end">Автор: {{ post.author }}</span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                    <div class="container">
                        <div class="card me-5">
                            <div class="card-header">Панель управления записью</div>
                            <div class="card-body">
                                {% if post in user.post_set.all %}
                                    <a href="{% url 'newsboard:post_comments' post.pk %}">
                                    <button type="button" class="btn btn-lg btn-outline-primary position-relative me-sm-3 mb-sm-3 mt-3">
                                        Отклики
                                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                        {{ post.comment_set.all|length }}
                                        </span>
                                    </button>
                                    </a>
                                    <a href="{% url 'newsboard:update' post.pk %}">
                                        <button class="btn btn-lg btn-outline-primary me-sm-3 mb-sm-3 mt-3">
                                            Редактировать
                                        </button>
                                    </a>
                                    <a href="#">
                                        <button class="btn btn-lg btn-outline-danger me-sm-3 mb-sm-3 mt-3">
                                            Удалить
                                        </button>
                                    </a>
                                {% else %}
                                    <a href="{% url 'newsboard:comment_create' post.pk %}">
                                        <button class="btn btn-lg btn-outline-primary me-sm-3 mb-sm-3 mt-3">
                                            Откликнуться
                                        </button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
            </div>
        </div>

    {% empty %}
        <div class="px-4 py-5 my-5 text-center">
            <h1 class="display-5 fw-bold">Тут пусто!</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">На сайте пока что нет ни одной записи. Станьте автором первой новости.</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <a href="{% url 'newsboard:create' %}">
                        <button type="button" class="btn btn-primary btn-lg px-4 gap-3">
                            Добавить новость
                        </button>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}